//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareServiceUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocEducation
    {
        public int Edu_id { get; set; }
        public int Doctor_id { get; set; }
        public string InstituteName { get; set; }
        public string Degree { get; set; }
        public string PassingYear { get; set; }
        public byte[] Certificate { get; set; }
    
        public virtual Doctor_P Doctor_P { get; set; }
    }
}
