//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareServiceUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drug()
        {
            this.PresciptionDetails = new HashSet<PresciptionDetail>();
        }
    
        public int Drug_id { get; set; }
        public string Name { get; set; }
        public int Generic_id { get; set; }
        public int Brand_id { get; set; }
        public string Strength { get; set; }
        public string Type { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Generic Generic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresciptionDetail> PresciptionDetails { get; set; }
    }
}
