//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareServiceUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presciption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Presciption()
        {
            this.PresciptionDetails = new HashSet<PresciptionDetail>();
        }
    
        public int Prescip_id { get; set; }
        public int Patient_id { get; set; }
        public int Doctor_id { get; set; }
        public System.DateTime Date { get; set; }
        public string BP { get; set; }
        public string Temp { get; set; }
        public string Weight { get; set; }
        public Nullable<int> Visit_no { get; set; }
        public Nullable<System.DateTime> NextDate { get; set; }
        public string Indication { get; set; }
    
        public virtual Doctor_P Doctor_P { get; set; }
        public virtual Patient_P Patient_P { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresciptionDetail> PresciptionDetails { get; set; }
    }
}
