//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareServiceUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresciptionDetail
    {
        public int PresDetail_id { get; set; }
        public int Prescip_id { get; set; }
        public int Drug_id { get; set; }
        public string Doze { get; set; }
        public string Duration { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Presciption Presciption { get; set; }
    }
}
